services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - server

  fe2:
    build:
      context: ./fe2
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3002:3002"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      PORT: 3002
    depends_on:
      - server
