name: SBOM

on:
  push:
    branches: [main]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - name: server
          - name: fe
          - name: fe2
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate source SBOMs
        run: |
          mkdir -p sbom
          GIT_SHA="${{ github.sha }}"
          GIT_SHA_SHORT="${GIT_SHA:0:7}"
          syft dir:./${{ matrix.target.name }} -o spdx-json > "sbom/${{ matrix.target.name }}-source-${GIT_SHA_SHORT}.spdx.json"

      - name: Build Docker images
        run: docker build -t ${{ matrix.target.name }}:latest -f ${matrix.target.name}/Dockerfile ${matrix.target.name}

      - name: Generate image SBOMs
        run: |
          GIT_SHA="${{ github.sha }}"
          GIT_SHA_SHORT="${GIT_SHA:0:7}"
          syft ${{ matrix.target.name }}:latest -o spdx-json > "sbom/${{ matrix.target.name }}-image-${GIT_SHA_SHORT}.spdx.json"

      - name: Upload SPDX SBOM artifacts
        uses: actions/upload-artifact@v6
        with:
          name: sbom-${{matrix.target.name }}-${{ github.sha }}-spdx
          path: sbom/${{ matrix.target.name }}-*.spdx.json
          retention-days: 90
